{{- if .Values.podDisruptionBudget.enabled }}
{{- range $name, $service := .Values.services }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hopdrop.fullname" $ }}-{{ $name | kebabcase }}
  labels:
    {{- include "hopdrop.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $.Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: {{ $name | kebabcase }}
---
{{- end }}
{{- end }}
